# Generated by Django 5.2.7 on 2025-12-15 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('activo', models.BooleanField(default=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_diarios', to='usuarios.usuario')),
            ],
            options={
                'indexes': [models.Index(fields=['instructor', 'fecha'], name='director_es_instruc_5eb580_idx')],
                'unique_together': {('instructor', 'fecha')},
            },
        ),
    ]
