# Generated by Django 5.2.8 on 2025-11-21 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
        ('usuarios', '0006_alter_usuario_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoinstructor',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='estadoinstructor',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_diarios', to='usuarios.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='estadoinstructor',
            unique_together={('instructor', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='estadoinstructor',
            index=models.Index(fields=['instructor', 'fecha'], name='director_es_instruc_5eb580_idx'),
        ),
    ]
