# Generated by Django 5.2.7 on 2025-10-26 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_titular', models.CharField(max_length=100)),
                ('titular_telefono', models.CharField(max_length=30)),
                ('nivel_clase', models.IntegerField()),
                ('disciplina_clase', models.CharField(choices=[('ski', 'Ski'), ('snow', 'Snow')], max_length=20)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('duracion', models.IntegerField()),
                ('cantidad_alumnos', models.IntegerField()),
                ('rut_usuario', models.ForeignKey(db_column='Rut_Usuario', on_delete=django.db.models.deletion.PROTECT, related_name='clases_asignadas', to='usuarios.usuario')),
            ],
        ),
    ]
