# Generated by Django 5.2.7 on 2025-10-26 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identificador',
            fields=[
                ('tipo_de_usuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut_usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('disciplina', models.CharField(blank=True, choices=[('ski', 'Ski'), ('snow', 'Snow'), ('ambos', 'Ambos')], max_length=20, null=True)),
                ('nivel_instructor', models.IntegerField(blank=True, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('idioma', models.CharField(blank=True, max_length=200, null=True)),
                ('id_centro', models.ForeignKey(blank=True, db_column='Id_Centro', null=True, on_delete=django.db.models.deletion.PROTECT, to='centros.centrodeesqui')),
                ('tipo_de_usuario', models.ForeignKey(db_column='Tipo_De_Usuario', on_delete=django.db.models.deletion.PROTECT, to='usuarios.identificador')),
            ],
        ),
    ]
