# Generated by Django 5.2.7 on 2025-10-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
