# Generated by Django 5.2.7 on 2025-10-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel_instructor',
            field=models.IntegerField(blank=True, choices=[('boleteria', 'boleteria'), ('instructor', 'instructor'), ('jefe_centro', 'jefe_centro')], null=True),
        ),
    ]
