# Generated by Django 5.2.7 on 2025-10-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_nivel_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel_instructor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
