# Generated by Django 5.2.7 on 2025-10-31 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_nivel_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_de_usuario',
            field=models.ForeignKey(choices=[('boleteria', 'boleteria'), ('instructor', 'instructor'), ('jefe_centro', 'jefe_centro')], db_column='Tipo_De_Usuario', on_delete=django.db.models.deletion.PROTECT, to='usuarios.identificador'),
        ),
    ]
