# Generated by Django 5.2.7 on 2025-11-02 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_tipo_de_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_de_usuario',
            field=models.ForeignKey(db_column='Tipo_De_Usuario', on_delete=django.db.models.deletion.PROTECT, to='usuarios.identificador'),
        ),
    ]
